# $OpenBSD$

COMMENT =	interpret and act on wait() status values

MODULES =	cpan
PKG_ARCH =	*
DISTNAME =	Proc-WaitStat-1.00
CATEGORIES =	sysutils

BUILD_DEPENDS =	${RUN_DEPENDS}
RUN_DEPENDS =	devel/p5-IPC-Signal

HOMEPAGE =	http://www.argon.org/~roderick/

MAINTAINER =	Markus Lude <markus.lude@gmx.de>

# Perl
PERMIT_PACKAGE =	Yes

.include <bsd.port.mk>
